"""Build a two-column Markdown comparison from the DEMO SUMMARY blocks."""

import re
import sys


def summary(path: str) -> tuple[dict[str, str], str]:
    text = open(path).read()
    block = re.search(r"===== DEMO SUMMARY =====\n(.*?)===== END SUMMARY =====", text, re.S)
    rows = {}
    if block:
        for line in block.group(1).strip().splitlines():
            key, _, value = line.partition(": ")
            rows[key] = value
    passed = [(n, s) for s, n in re.findall(r"^(PASSED|FAILED) (\S+)", text, re.M)]
    result = re.search(r"=+ (.*(?:passed|failed).*) =+\s*$", text, re.M)
    status = "; ".join(f"`{n.split('::')[-1]}` {s}" for n, s in passed if s != "SKIPPED")
    return rows, f"{status} ({result.group(1) if result else 'no result'})"


stock, stock_status = summary(sys.argv[1])
fixed, fixed_status = summary(sys.argv[2])
print("# Side-by-side: stock control-arena 20.0.1 vs fixed branch\n")
print("Generated by `scripts/side_by_side.py` from `results/stock-20.0.1.txt` and `results/fixed.txt`.\n")
print("| | Stock 20.0.1 (bug) | Fixed branch |")
print("|---|---|---|")
for key in dict.fromkeys([*stock, *fixed]):
    print(f"| {key} | `{stock.get(key, '')}` | `{fixed.get(key, '')}` |")
print(f"| **test result** | {stock_status} | {fixed_status} |")
